version: "3.9" # optional since v1.27.0
services:
  janus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./recordings:/recordings
    env_file:
      - .env
    restart: always
    network_mode: "host"
    
  converter:
    build:
      context: .
      dockerfile: converter.Dockerfile
    volumes:
      - ./recordings:/recordings
    env_file:
      - .env
    restart: always
    network_mode: "host"

volumes:
  recordings:
    external: true
