version: "3.9" # optional since v1.27.0
services:
  janus-multistreaming:
    build: .
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
