version: "3.9" # optional since v1.27.0
services:
  janus-multistreaming:
    network_mode: "host"
    environment:
      URI_CONV_ENDPOINT: ${URI_CONV_ENDPOINT}
      URI_CONV_AUTH_TOKEN: ${URI_CONV_AUTH_TOKEN}
    build:
      context: .
      args:
        COMMIT_HASH: ${COMMIT_HASH}
        
